language: node_js
node_js:
  - node
  - 10
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - NODE_ENV=production npm run build
  - semantic-release
notifications:
  email: false
sudo: false
